container-with-most-water/container-with-most-water.cpp
Please review the necessary changes..
fix #9
=> Time: 80 ms (81.18%), Space: 58.9 MB (81.33%) - LeetHub

arithmetic-slices/arithmetic-slices.cpp
=> Added solution to problem arithmetic-slices

construct-binary-tree-from-preorder-and-inorder-traversal/construct-binary-tree-from-preorder-and-inorder-traversal.cpp
Hi @samyakjain10,
I have added the solution to the problem construst binary tree from preorder and inorder traversal regarding issue #8 
fix #8
=> Added solution to construst binary tree from preorder and inorder traversal

binary-search/binary-search.cpp
Hi @samyakjain10,
I have added the solution to the problem binary search regarding issue #5.
=> Added solution to problem binary search

backspace-string-compare/backspace-string-compare.cpp
=> Add: Added the solution of backspace-string-compare problem in cpp

complex-number-multiplication/complex-number-multiplication.cpp
=> Add: Added the solution of Complex Number Multiplication problem in cpp

binary-search/binary-search.cpp, fibonacci-number/fibonacci-number.cpp
I have added the solution to the problem binary search regarding issue #24.
=> Added Solution to fibonacci-number - Leetcode

longest-increasing-subsequence/lis.cpp
=> Added solution to Longest Increasing Subsequence

decode-ways/decodeWays.cpp
=> Added solution to Decode Ways

is-subsequence/is_subsequence.cpp
=> Solved Is-Subsequence . Fixed issue #30

majority-element/majority_element_another_approach.cpp
Please accept my pull request sir.
=> Solved this problem using another approach in cpp

palindrome-linked-list/pallindrome-linked list.cpp
=> added solution to pallindrome linked list

binary-tree-level-order-traversal/binary-tree-level-order-traversal.cpp
=> add solution to level order traversal

Design-Twitter.cpp
=> Problem Design Twitter CPP Solution

README.md
=> ReadMe Added

power-of-two/power_of_two.cpp
Hey there I have added the solution to the issue #48 . Kindly merge it under hacktoberfest accepted label and let me know if there are any issues. Thank you.......!!!!!
=> Time: 0 ms (100%), Space: 6 MB (21.37%) - LeetHub

Find First and Last Position of Element in Sorted Array/Find First and Last Position of Element in Sorted Array.cpp, Find First and Last Position of Element in Sorted Array/Readme.md
Done  Find First and Last Position of Element in Sorted Array using cpp
=>  Find First and Last Position of Element in Sorted Array

beautiful-arrangement/Beautiful Arrangement.cpp
=> Problem Beautiful Arrangement CPP Solution

breadth-first-search/breadth-first-search.cpp
Breadth First Search
A graph traversal algorithm using C++
=> Breadth First Search

flip-binary-tree/flipbinarytree.cpp
=> add flip a binary tree

house-robber/House Robber.cpp
=> Problem House Robber CPP Solution

decode-ways/decode-ways.cpp
=> add solution to decode ways

pascals-triangle-ii/pascals triangle2.cpp
add solution to pascals triangle II
=> add solution to pascals triangle II

linked-list-cycle/README.md, linked-list-cycle/linked-list-cycle.cpp
linked-list-cycle solution added issue #73 solved using C++ language
=> linked-list-cycle solution added issue #73 solved

postorder.cpp
I have made a program of postorder traversal using cpp.
Thanks and regards
GarvitV957
=> Postorder traversal
